// client/src/components/CertificatePreview.jsx
import React, { useEffect, useRef } from 'react';
import JsBarcode from 'jsbarcode';
import { format } from 'date-fns';
import { MapPin } from 'lucide-react'; // Optional, or just use simple styling

const DefaultLogo = () => (
  <svg width="40" height="40" viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect x="35" y="10" width="30" height="80" fill="black" />
    <rect x="10" y="35" width="80" height="30" fill="black" />
  </svg>
);

const numberToWords = (num) => {
  const n = parseInt(num, 10);
  if (isNaN(n)) return '';
  const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
  const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
  if (n === 0) return 'Zero';
  if (n < 20) return ones[n];
  if (n < 100) return tens[Math.floor(n / 10)] + (n % 10 !== 0 ? ' ' + ones[n % 10] : '');
  return n.toString();
};

const CertificatePreview = React.forwardRef(({ data }, ref) => {
  const barcodeRef = useRef(null);

  useEffect(() => {
    if (data.certificateId && barcodeRef.current) {
      JsBarcode(barcodeRef.current, data.certificateId, {
        format: "CODE128",
        width: 1,
        height: 25,
        displayValue: true,
        fontSize: 10,
        margin: 0,
        lineColor: "#000000"
      });
    }
  }, [data.certificateId]);

  const prefix = data.patientTitle || '';
  const currentDateFormatted = data.date ? format(new Date(data.date), 'dd MMM yyyy') : '';
  const startDateFormatted = data.startDate ? format(new Date(data.startDate), 'dd MMM yyyy') : '';
  const restDaysWord = numberToWords(data.restDays);

  return (
    <div className="certificate-print" ref={ref} id="certificate-print">
      {/* Header section */}
      <div className="cert-header-row">
        <div className="cert-logo-container">
          {data.clinicLogo ? (
            <img src={data.clinicLogo} alt="Clinic Logo" className="cert-logo" />
          ) : (
            <DefaultLogo />
          )}
        </div>
        <div className="cert-clinic-info">
          <div className="cert-dept-name">{data.departmentName || 'HEALTH AND FAMILY WELFARE DEPARTMENT'}</div>
          <div className="cert-clinic-name">{data.clinicName || 'COMMUNITY HEALTH CENTRE, BAROH'}</div>
          <div className="cert-clinic-address">
            {data.clinicAddress || 'TEH. BAROH, DISTT, KANGRA (H.P)'}
          </div>
        </div>
      </div>

      <hr className="cert-divider" />

      {/* Body Wrapper */}
      <div className="cert-body-wrapper">
        {/* Title */}
        <div className="cert-title">MEDICAL CERTIFICATE</div>

        {/* Date */}
        <div className="cert-date-row">
          Date: <span className="cert-underline">............ {currentDateFormatted || '[Date]'} ............</span>
        </div>

        {/* Patient Info */}
        <table className="cert-info-table">
          <tbody>
            <tr>
              <td className="col-label">Name</td>
              <td className="col-colon">:</td>
              <td className="col-value">{prefix} {data.patientName || '[Patient Name]'}</td>
            </tr>
            <tr>
              <td className="col-label">Age</td>
              <td className="col-colon">:</td>
              <td className="col-value">{data.age ? `${data.age} Years` : '[Age]'}</td>
            </tr>
            <tr>
              <td className="col-label">Gender</td>
              <td className="col-colon">:</td>
              <td className="col-value">{data.gender || '[Gender]'}</td>
            </tr>
            <tr>
              <td className="col-label">Address</td>
              <td className="col-colon">:</td>
              <td className="col-value">{data.patientAddress || '[Address]'}</td>
            </tr>
          </tbody>
        </table>

        <hr className="cert-divider" />

        {/* Diagnosis Info */}
        <div className="cert-diagnosis-section">
          <div className="col-label">Diagnosis :</div>
          <div className="col-value diagnosis-text">{data.diagnosis || '[Diagnosis]'}</div>
        </div>
        
        <div className="cert-rest-section">
          <span className="col-label">Recommended Rest Period :</span>
          <span className="col-value" style={{ marginLeft: '10px' }}>{data.restDays || '[X]'} ({restDaysWord}) Days</span>
        </div>

        <hr className="cert-divider" />

        {/* Statement */}
        <div className="cert-paragraph">
          This is to certify that {prefix} {data.patientName || '[Patient Name]'}, aged {data.age || '[Age]'} years, was examined on {currentDateFormatted || '[Date]'} and diagnosed with {data.diagnosis || '[Diagnosis]'}.
        </div>

        <div className="cert-paragraph">
          The patient is advised to take rest for {data.restDays || '[X]'} ({restDaysWord}) days from {startDateFormatted || '[Start Date]'}.
        </div>

        <div className="cert-instructions-title">
          Instructions/Recommendations :
        </div>
        <div className="cert-paragraph">
          {data.instructions || 'Take plenty of rest, drink fluids, and follow the prescribed medication.'}
        </div>
      </div>

      {/* Footer */}
      <div className="cert-footer">
        <div className="cert-stamp-left">
          {data.stampImage && <img src={data.stampImage} alt="Stamp" style={{ transform: 'rotate(-70deg)' }} className="cert-stamp" />}
        </div>

        <div className="cert-doctor-section">
          <div className="cert-signature-box">
            {data.signatureImage && <img src={data.signatureImage} alt="Signature" />}
            {data.stampImage && <img src={data.stampImage} alt="Stamp" className="cert-stamp-overlay" />}
          </div>
          <hr className="cert-sign-line" style={{ borderTop: '1px solid black', width: '100%', margin: '5px 0' }} />
          <div className="cert-doctor-name" style={{ textAlign: 'center' }}>Doctor's Signature</div>
        </div>
      </div>

      {/* Bottom section pushes to the end of the A4 page */}
      <div style={{ marginTop: 'auto' }}>
        <div className="cert-barcode-section">
          <svg ref={barcodeRef}></svg>
        </div>

        {/* Bottom Note */}
        <div className="cert-bottom-note">
          <div>This certificate is valid only for the period mentioned above. Any extension requires re-evaluation by the attending physician.</div>
          <div>This is a computer-generated document.</div>
        </div>
      </div>
    </div>
  );
});

export default CertificatePreview;

// client/src/components/CertificatePreview.svelte
<script>
  import { onMount } from 'svelte';
  import JsBarcode from 'jsbarcode';

  export let data = {};
  
  let barcodeNode;

  // Svelte reactivity for barcode
  $: if (barcodeNode && data.certificateId) {
    JsBarcode(barcodeNode, data.certificateId, {
      format: "CODE128",
      lineColor: "#000",
      width: 1.5,
      height: 40,
      displayValue: true,
      fontSize: 14,
      margin: 0
    });
  }
</script>

<div class="certificate-print mx-auto relative shadow-2xl flex flex-col justify-between">
  <!-- Header -->
  <div class="text-center mb-8 border-b-2 border-black pb-4">
    <h2 class="text-xl font-bold uppercase tracking-wider mb-2">{data.departmentName || '[Department Name]'}</h2>
    <h1 class="text-2xl font-black uppercase tracking-widest">{data.clinicName || '[Clinic/Hospital Name]'}</h1>
    <p class="text-sm mt-2">{data.clinicAddress || '[Clinic Address]'}</p>
  </div>

  {#if data.clinicLogo}
    <img src={data.clinicLogo} alt="Clinic Logo" class="absolute top-12 left-16 w-24 h-24 object-contain opacity-80" />
  {/if}

  <div class="text-center font-bold text-2xl tracking-[0.2em] mb-8 underline underline-offset-4">
    MEDICAL CERTIFICATE
  </div>

  <div class="flex justify-between items-start mb-10 text-sm">
    <div class="w-1/2">
      <div class="grid grid-cols-[100px_auto] gap-2 mb-2">
        <span class="font-bold">Name</span>
        <span>: {data.patientTitle || 'Mr.'} {data.patientName || '[Patient Name]'}</span>
      </div>
      <div class="grid grid-cols-[100px_auto] gap-2 mb-2">
        <span class="font-bold">Age</span>
        <span>: {data.age || '[Age]'}</span>
      </div>
      <div class="grid grid-cols-[100px_auto] gap-2 mb-2">
        <span class="font-bold">Gender</span>
        <span>: {data.gender || '[Gender]'}</span>
      </div>
      <div class="grid grid-cols-[100px_auto] gap-2">
        <span class="font-bold">Address</span>
        <span>: {data.patientAddress || '[Address]'}</span>
      </div>
    </div>
    <div class="text-right flex flex-col items-end gap-4">
      <div>
        <span class="mr-2">Date:</span>
        <span class="border-b border-black border-dashed pb-1 min-w-[120px] inline-block text-center">
          {data.date || '[Date]'}
        </span>
      </div>
      <!-- Barcode -->
      <div class="mt-2">
        <svg bind:this={barcodeNode}></svg>
      </div>
    </div>
  </div>

  <div class="border-t-2 border-b-2 border-black py-4 mb-8">
    <div class="font-bold mb-2 text-lg">Diagnosis :</div>
    <div class="mb-4 text-lg italic">{data.diagnosis || '[Diagnosis]'}</div>
    <div class="font-bold text-lg">Recommended Rest Period : <span class="border-b border-black px-4">{data.restDays || '[X]'}</span> Days</div>
  </div>

  <div class="flex-grow text-justify leading-relaxed text-base mb-8">
    <p class="mb-4">
      This is to certify that {data.patientTitle || 'Mr.'} <strong>{data.patientName || '[Patient Name]'}</strong>, aged {data.age || '[Age]'} years, was examined on <strong>{data.date || '[Date]'}</strong> and diagnosed with <strong>{data.diagnosis || '[Diagnosis]'}</strong>.
    </p>
    <p class="mb-6">
      The patient is advised to take rest for <strong>{data.restDays || '[X]'}</strong> days from <strong>{data.startDate || '[Start Date]'}</strong> to <strong>{data.endDate || '[End Date]'}</strong>.
    </p>
    <div class="font-bold mb-2">Instructions/Recommendations :</div>
    <p class="whitespace-pre-line">{data.instructions || 'Take plenty of rest, drink fluids, and follow the prescribed medication.'}</p>
  </div>

  <!-- Footer -->
  <div class="flex justify-between items-end mt-12 pt-8 relative">
    <div class="w-1/3 text-center">
      {#if data.stampImage}
        <img src={data.stampImage} alt="Official Stamp" class="h-24 object-contain mx-auto mb-2 opacity-80" />
      {:else}
        <div class="h-24 flex items-center justify-center border-2 border-dashed border-gray-300 text-gray-400 mb-2 rounded-full w-24 mx-auto">
          Stamp
        </div>
      {/if}
      <div class="border-t border-black pt-1 font-bold text-sm">Official Stamp</div>
    </div>

    <div class="w-1/3 text-center">
      {#if data.signatureImage}
        <img src={data.signatureImage} alt="Doctor Signature" class="h-16 object-contain mx-auto mb-2" />
      {:else}
        <div class="h-16 mb-2"></div>
      {/if}
      <div class="border-t border-black pt-1 font-bold text-sm">Doctor's Signature</div>
    </div>
  </div>
</div>
